[2021-08-04 11:45:22,164] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2021-08-03T00:00:00+00:00 [queued]>
[2021-08-04 11:45:22,172] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2021-08-03T00:00:00+00:00 [queued]>
[2021-08-04 11:45:22,173] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 11:45:22,173] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-08-04 11:45:22,173] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 11:45:22,224] {taskinstance.py:1087} INFO - Executing <Task(SqliteOperator): creating_table> on 2021-08-03T00:00:00+00:00
[2021-08-04 11:45:22,235] {standard_task_runner.py:52} INFO - Started process 15957 to run task
[2021-08-04 11:45:22,289] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'creating_table', '2021-08-03T00:00:00+00:00', '--job-id', '27', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpuxqhe23i', '--error-file', '/tmp/tmpxve2vae8']
[2021-08-04 11:45:22,291] {standard_task_runner.py:77} INFO - Job 27: Subtask creating_table
[2021-08-04 11:45:22,427] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.creating_table 2021-08-03T00:00:00+00:00 [running]> on host airflowvm
[2021-08-04 11:45:22,532] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=creating_table
AIRFLOW_CTX_EXECUTION_DATE=2021-08-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-03T00:00:00+00:00
[2021-08-04 11:45:22,534] {sqlite.py:63} INFO - Executing: 
            CREATE TABLE IF NOT EXIST users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
            
[2021-08-04 11:45:22,542] {base.py:69} INFO - Using connection to: id: db_sqlite. Host: /home/airflow/airflow/airflow.db, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-08-04 11:45:22,544] {dbapi.py:204} INFO - Running statement: 
            CREATE TABLE IF NOT EXIST users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
            , parameters: []
[2021-08-04 11:45:22,544] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/providers/sqlite/operators/sqlite.py", line 65, in execute
    hook.run(self.sql, parameters=self.parameters)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 184, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/sandbox/lib/python3.8/site-packages/airflow/hooks/dbapi.py", line 208, in _run_command
    cur.execute(sql_statement)
sqlite3.OperationalError: near "EXIST": syntax error
[2021-08-04 11:45:22,553] {taskinstance.py:1524} INFO - Marking task as FAILED. dag_id=user_processing, task_id=creating_table, execution_date=20210803T000000, start_date=20210804T114522, end_date=20210804T114522
[2021-08-04 11:45:22,622] {local_task_job.py:151} INFO - Task exited with return code 1
