[2021-08-04 11:46:53,002] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-08-03T00:00:00+00:00 [queued]>
[2021-08-04 11:46:53,014] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-08-03T00:00:00+00:00 [queued]>
[2021-08-04 11:46:53,015] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 11:46:53,016] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-08-04 11:46:53,017] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-08-04 11:46:53,057] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-08-03T00:00:00+00:00
[2021-08-04 11:46:53,071] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-08-03T00:00:00+00:00', '--job-id', '29', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpz10x7k_n', '--error-file', '/tmp/tmpfi9402lx']
[2021-08-04 11:46:53,061] {standard_task_runner.py:52} INFO - Started process 16039 to run task
[2021-08-04 11:46:53,079] {standard_task_runner.py:77} INFO - Job 29: Subtask is_api_available
[2021-08-04 11:46:53,169] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-08-03T00:00:00+00:00 [running]> on host airflowvm
[2021-08-04 11:46:53,233] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-08-03T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-03T00:00:00+00:00
[2021-08-04 11:46:53,235] {http.py:101} INFO - Poking: api/
[2021-08-04 11:46:53,244] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-08-04 11:46:53,247] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-08-04 11:46:54,136] {base.py:243} INFO - Success criteria met. Exiting.
[2021-08-04 11:46:54,147] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20210803T000000, start_date=20210804T114653, end_date=20210804T114654
[2021-08-04 11:46:54,233] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-04 11:46:54,278] {local_task_job.py:151} INFO - Task exited with return code 0
